FROM alpine:3.14

RUN apk --no-cache add curl

RUN mkdir -p /workdir /crts

WORKDIR /workdir

COPY generate_ca.sh /workdir/
COPY generate_crt.sh /workdir/

RUN chmod +x /workdir/*.sh && /workdir/generate_ca.sh

CMD ["apiserver.com,127.0.0.1","apiserver"]

ENTRYPOINT ["/workdir/generate_crt.sh"]


