## httpserver service


## deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  labels:
    app: httpserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
      - name: httpserver
        image: ezrealtest/httpserver:v0.0.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          request:
            cpu: 250m
            memory: 64Mi  
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh","-c","/lifecycle/post-start.sh"]      
          preStop:
            exec:
              command: ["/bin/sh","-c",,"kill -SIGTERM $(cat /workdir/.pidfile)"]
        livenessProbe:
          httpGet:
            port: 8080
            path: /live
          initialDelaySeconds: 1  
          #terminationGracePeriodSeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
        readynessProbe:
          httpGet:
            port: 8080
            path: /ready   
          initialDelaySeconds: 1
          #terminationGracePeriodSeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          exec:
            command: ["/bin/sh","-c","ls /lifecycle/started"]  
          initialDelaySeconds: 5
          #terminationGracePeriodSeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1  
        volumeMounts:
          - name: config
            mountPath: /workdir/conf  
      lifeCycle: # pod lifecycle
        terminationGracePeriodSeconds: 10  
        readinessGates:
        - conditionType: "www.example.com/feature-1"
      volumes:
        - name: config
          configMap:
            name: httpserver-config

            
## configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpserver-config
data:
  loglevel: 3
    